---
title: "STATS 782 Assignment 4; University of Auckland, Semester 1"
date: 'Due Date: 23:59 NZ Time, Thursday 2 Jun 2022'
output:
  html_document: default
  pdf_document: default
---

### "Your name", "UPI"

I have read the declaration on the cover sheet and confirm my agreement with it.

## Question 1

### a)

```{r}


# p4 <- pgon(c(0,1,1), c(0,0,1,1))
# a  <- seq(0, 2*pi, length.out=9)[1:8]
# p8 <- pgon(sin(a), cos(a))
```

### b)

```{r}


# pts(p4)
```

### c)

```{r}


# length(p8)
```

### d)

```{r}


# p8
```

### e)

```{r fig.width=5, fig.height=4}


# par(mar=c(4, 4, 0.1, 0.1))
# plot(p8, col="red")
# plot(p4, col="#00000080", border=NA, add=TRUE)
```

### f)

```{r}


# -p4
# p4 + c(1,2)
# p4 - pts(p8)[1,]
# c(1, 1) - p4
```

### g)

```{r}


# (l3 <- colygon(c(-1, 0, 1), c(-1, 1), col="yellow"))
# (l8 <- colygon(p8, col="green"))
```

### h)

```{r fig.width=4, fig.height=4}


# plot(l8)
```

### i)

```{r}


# l8 + c(0, 1)
# -l8
```


## Question 2

(No need to answer here, upload the final package to Canvas!)

